### ISSUE TITLE
StopAsyncIteration exception in Pyhton 3.7

### ISSUE THREAD

**Issue by radosuav** [DHI-GRAS/itsybitsy#3]
With Python 3.7.6 I get the following exception when using itsybitsy within vito_download:
```
In [1]: runfile('/data/python_packages/wapor-et-look/prepare_run_ETLook.py', wdir='/data/python_packages/wapor-et-look')
  0%|          | 0/32 [00:05<?, ?it/s]
Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/itsybitsy/spider/asynchronous.py", line 159, in crawl
    yield loop.run_until_complete(link)

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/nest_asyncio.py", line 59, in run_until_complete
    return f.result()

  File "/home/ubuntu/anaconda3/lib/python3.7/asyncio/futures.py", line 181, in result
    raise self._exception

  File "/home/ubuntu/anaconda3/lib/python3.7/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)

StopAsyncIteration


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/itsybitsy/spider/asynchronous.py", line 161, in crawl
    raise StopIteration

StopIteration


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/data/python_packages/wapor-et-look/prepare_run_ETLook.py", line 19, in <module>
    ConfigFileInterface.prepare_and_run_ETLook(config_file)

  File "/data/python_packages/wapor-et-look/pyWAPOR/ConfigFileInterface.py", line 57, in prepare_and_run_ETLook
    landcover)

  File "/data/python_packages/wapor-et-look/pyWAPOR/Pre_ETLook.py", line 143, in prepare_level2
    username_vito, password_vito)

  File "/data/python_packages/wapor-et-look/pyWAPOR/Collect/PROBAV/NDVI.py", line 10, in main
    download_data(download_dir, start_date, end_date, latitude_extent, longitude_extent, username, password)

  File "/data/python_packages/wapor-et-look/pyWAPOR/Collect/PROBAV/DataAccess.py", line 60, in download_data
    downloaded_files = list(local_files)

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/vito_download/download.py", line 100, in _recursive_download
    for url in crawler:

RuntimeError: generator raised StopIteration
```

With Python 3.6.10 the download works fine but I have to use
```
import nest_asyncio
nest_asyncio.apply()
```

**Comment by dionhaefner** [comment]
This is the cause of the exception you are seeing:

https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app

Suggested fix is to replace this line

https://github.com/DHI-GRAS/itsybitsy/blob/81eca61a571d0791a8a18d7f4a19585012eedf86/itsybitsy/spider/asynchronous.py#L161

with a simple `return`. I'm not sure whether that will make it work though, since async support changed a lot in recent Python versions.

**Comment by radosuav** [comment]
Thanks @dionhaefner! Your suggested fix does solve the problem. But I will let others with more knowledge assess all the implications ;)

**Comment by dionhaefner** [comment]
Did you still need `nest_asyncio`?

**Comment by radosuav** [comment]
Yes, nest_asyncio is still necessary in both Python 3.6 and 3.7. Otherwise I get the following:
```
Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/itsybitsy/spider/asynchronous.py", line 159, in crawl
    yield loop.run_until_complete(link)

  File "/home/ubuntu/anaconda3/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()

  File "/home/ubuntu/anaconda3/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/data/python_packages/wapor-et-look/prepare_run_ETLook.py", line 19, in <module>
    ConfigFileInterface.prepare_and_run_ETLook(config_file)

  File "/data/python_packages/wapor-et-look/pyWAPOR/ConfigFileInterface.py", line 57, in prepare_and_run_ETLook
    landcover)

  File "/data/python_packages/wapor-et-look/pyWAPOR/Pre_ETLook.py", line 143, in prepare_level2
    username_vito, password_vito)

  File "/data/python_packages/wapor-et-look/pyWAPOR/Collect/PROBAV/NDVI.py", line 10, in main
    download_data(download_dir, start_date, end_date, latitude_extent, longitude_extent, username, password)

  File "/data/python_packages/wapor-et-look/pyWAPOR/Collect/PROBAV/DataAccess.py", line 70, in download_data
    downloaded_files = list(local_files)

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/vito_download/download.py", line 88, in _recursive_download
    base_url_normalized = next(crawler)

  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/itsybitsy/spider/asynchronous.py", line 163, in crawl
    loop.run_until_complete(crawler.aclose())

  File "/home/ubuntu/anaconda3/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()

  File "/home/ubuntu/anaconda3/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running
```

In Python 3.6 the exception is essentially the same, just the line numbers are a bit different.

**Comment by dionhaefner** [comment]
`itsybitsy` works fine for me in Python 3.7.7. So maybe this has something to do with one of the other packages - if any of them is async, you would expect to see this error.

**Comment by j08lue** [comment]
So, is there anything we should change with `itsybitsy` or should the client libary (`vito_download`, in this case), be changed to better handle the completion of the iterator?

**Comment by dionhaefner** [comment]
I’m not sure. Using nest_asyncio is an acceptable solution, but I think it would be best to try and understand where the error comes from first. Maybe confirm that itsybitsy works standalone and work from there.

**Comment by radosuav** [comment]
So what did we conclude? Should I:
1. Make a commit to modify asynchronous.py [as suggested above](https://github.com/DHI-GRAS/itsybitsy/issues/3#issuecomment-659997758)?
2.  Add 
```
import nest_asyncio
nest_asyncio.apply()
```
to where? Itsybitsy, vito-download or to my code which uses vito-download?

**Comment by dionhaefner** [comment]
1. Yes
2. Your code (until someone decides to investigate this properly)
